### ISSUE TITLE
Not Downloading/Connecting to Peers

### ISSUE THREAD

**Issue by Conmyster** [binhex/arch-rtorrentvpn#117]
Hello 

So I have the docker container installed on a Debain 9.7 VM. 

I can access the WebUI however when I add a torrent it connects to the trackers fine by the looks of things but then it fails to download/connect to peers. It also show the torrent as Queued. 

![image](https://user-images.githubusercontent.com/5269015/59942410-7c4d0a00-9457-11e9-9739-a23562135d45.png)

I am unsure which logs you require so please do tell me and I will provide them to you.

**Comment by Conmyster** [comment]
Sorry, my fault permissions issue

**Comment by Toqozz** [comment]
Just commenting on this in case it helps someone else.  I had similar symptoms, but it turns out my issue was caused by mergerfs mount options.  rTorrent requires `mmap` to work correctly, and some configurations disable it by default.

I'm using OMV and I needed to change `cache.files=off` to `cache.files=partial` in the mount options for union filesystems.

You can read more about `mmap` and `cache` options in the mergerfs README: ([permalink](https://github.com/trapexit/mergerfs/blob/46de43d4ade9dd2894d2ea8d87ec7ef2cded44da/README.md))
StackExchange post: https://unix.stackexchange.com/questions/183534/rtorrent-wont-start-downloading-to-9p-shared-folder
