### ISSUE TITLE
Scheduler in rutorrent keeps turning off

### ISSUE THREAD

**Issue by ryanmurray** [binhex/arch-rtorrentvpn#13]
Up until a recent update i was able to have the scheduler in rutorrent interface work just fine but recently if i close out of the web window the scheduler can become ignored because i repopen and notice it downloading at full speed.

**Comment by binhex** [comment]
ok im not seeing this particular issue at the moment, i personally make extensive use of the scheduler as my isp has caps on usage during certain times and i can say hand on heart it works fine. i did originally have issues with the scheduler, where it was not being triggered, this was due to not triggering the  initialisation of the  plugins, but i believe this is now fixed, your not by any chance running both flood and rutorrent webui are you?, this could stuff things up as one could trample over the settings of the other?.
