### ISSUE TITLE
access through tmux in terminal

### ISSUE THREAD

**Issue by disrupted** [binhex/arch-rtorrentvpn#163]
rTorrent used to run inside a tmux session by default, so I could connect to it and use it without graphical frontend. In the newest version I can no longer access it this way. I still see the rtorrent process using htop but when I run `tmux ls` it says that there are no sessions.

**Comment by picodexter** [comment]
You are probably running `tmux ls` as root, who doesn't have any active tmux sessions, but if you look at the running tmux sessions via `ps aux | grep tmux`, you can see that rtorrent is executed in a tmux by user nobody.

So in order to get into that tmux session, you can execute: `sudo -u nobody tmux attach-session -t rt`

**Comment by disrupted** [comment]
@picodexter excellent, thank you!
