### ISSUE TITLE
Permissions problem preventing startup

### ISSUE THREAD

**Issue by wolfcry0** [binhex/arch-rtorrentvpn#45]
I haven't been able to get the container working so far, it seems to have some issues with permissions of a file in the logs.

`2018-02-27 08:51:13,195 DEBG 'rtorrent-script' stdout output:
error connecting to /tmp/tmux-1004/default (Permission denied)`

`2018-02-27 08:52:12,546 DEBG 'rtorrent-script' stderr output:
/home/nobody/getvpnextip.sh: line 9: /home/nobody/vpn_external_ip.txt: Permission denied`

These are the relevant file permissions:

`--------w- 1 root   root    15 Feb 27 08:51 vpn_external_ip.txt`

`/tmp/tmux-1004/default` doesn't seem to exist at all, the directory `/tmp/tmux-1004` does though.

**Comment by mrcirillo** [comment]
I had a similar issue a while ago because of the umask I had specified. vpn_external_ip.txt and the other file are created by the root user. You can connect a console and chown them to fix it once or use a different umask (switching to 000 fixed it for me) as a permanent solution.

I haven't encountered the tmux tmp problem but it seems like it could be the same cause.
