### ISSUE TITLE
chown does not finish

### ISSUE THREAD

**Issue by braindump** [binhex/arch-rtorrentvpn#94]
When stating the container, it hangs after `2019-02-15 18:38:41.060417 [info] ENABLE_AUTODL_IRSSI defined as 'no'` while `chown -R 1000:1000 /etc/webapps /usr/share/webapps /usr/share/nginx/html /etc/nginx /etc/php /run/php-fpm /var/lib/nginx /var/log/nginx /etc/privoxy /home/nobody /etc/webapps/flood /usr/share/autodl-irssi` does not seem to finish.

**Comment by enoch85** [comment]
It can take very long time, especially if you are running on a low spec server.

**Comment by GottZ** [comment]
would be benefitial if the container would ship with a set uid/gid so chown would not be required at all.
luckily the overlay2 driver received an update where it only creqtes new meta data. in the past it blew up the image size when doing chown.
tbh this is the only container image i know that ships with 0:0 as default.

**Comment by braindump** [comment]
> It can take very long time, especially if you are running on a low spec server.

It's running on a high spec server and still takes about an hour. But yes it does indeed finish at some point so this one can be closed. Thanks

**Comment by binhex** [comment]
> would be benefitial if the container would ship with a set uid/gid so chown would not be required at all.

not possible, i have seen a LOT of cases where people want to change the uid and gid to match permissions for the volume mounts.

> tbh this is the only container image i know that ships with 0:0 as default.

there is no default, what is shown in the readme is an example command, you can tailor the PUID and PGID to whatever you want, i only use 0:0 cos i know most/all systems have a root account and thus the example SHOULD work.

 the issue is related to overlay2 which was/is crap for some reason when it comes to chown/chmod, i use btrfs storage driver and chown/chmod takes less than a second.
